name: AllowPlayers
version: ${project.version}
description: Allow players onto your server when minecraft.net is down
author: jgeboski
main: org.AllowPlayers.AllowPlayers
softdepend: ['AdminCmd', 'Essentials']

commands:
  allowplayers:
    description: Manage AllowPlayers
    aliases: ['ap']
    usage: /<command> [check|reload]
  onlinemode:
    description: Enable/Disable online mode
    aliases: ['om']
    usage: /<command> [status|enable|disable]

permissions:
  allowplayers.ap:
    description: Access the allowplayers command
    default: op
  allowplayers.ap.check:
    description: Force a Minecraft.net check
    default: op
  allowplayers.ap.reload:
    description: Reload the configuration
    default: op
  allowplayers.onlinemode:
    description: Set the server's online mode
    default: op
  allowplayers.msg.notify:
    description: View Minecraft.net status messages
    default: op
