name: AllowPlayers
version: ${project.version}
description: Allow players onto your server when minecraft.net is down
author: jgeboski
main: org.AllowPlayers.AllowPlayers
softdepend: ['AdminCmd', 'CraftIRC', 'Essentials', 'Essentials-3']

commands:
  allowplayers:
    description: Manage AllowPlayers
    aliases: ['ap']
    usage: |
      /<command> [check|enable|disable|reload]
      /<command> set <player> <IP>

  onlinemode:
    description: Enable/Disable online mode
    aliases: ['om']
    usage: /<command> [status|enable|disable]

permissions:
  allowplayers.command.ap:
    description: Access the allowplayers command
    default: op

  allowplayers.command.check:
    description: Force a Minecraft.net check
    default: op
    children:
      allowplayers.command.ap: true

  allowplayers.command.reload:
    description: Reload the configuration
    default: op
    children:
      allowplayers.command.ap: true

  allowplayers.command.onlinemode:
    description: Set the server's online mode
    default: op
    children:
      allowplayers.command.ap: true

  allowplayers.command.set:
    description: Set a player's IP
    default: op
    children:
      allowplayers.command.ap: true

  allowplayers.command.toggle:
    description: Toggle AllowPlayers on or off
    default: op
    children:
      allowplayers.command.ap: true

  allowplayers.message.notify:
    description: View Minecraft.net status messages
    default: op

  # For compatibility (these are deprecated)
  allowplayers.ap:
    description: 'Deprecated, use: allowplayers.command.ap'
    default: op
    children:
      allowplayers.command.ap: true

  allowplayers.ap.check:
    description: 'Deprecated, use: allowplayers.command.check'
    default: op
    children:
      allowplayers.command.check: true

  allowplayers.ap.reload:
    description: 'Deprecated, use: allowplayers.command.reload'
    default: op
    children:
      allowplayers.command.reload: true

  allowplayers.onlinemode:
    description: 'Deprecated, use: allowplayers.command.onlinemode'
    default: op
    children:
      allowplayers.command.onlinemode: true

  allowplayers.msg.notify:
    description: 'Deprecated, use: allowplayers.message.notify'
    default: op
    children:
      allowplayers.message.notify: true
