name: AllowPlayers
version: 0.2.0
description: Allow players onto your server when minecraft.net is down
author: jgeboski
main: org.AllowPlayers.AllowPlayers

commands:
  allowplayers:
    description: Manage and view pending requests
    aliases: ['ap']
    usage: /<command> [[pending|reload] [accept|reject]] [[pagenumber] [playername]]
  mcnet:
    description: Minecraft.net management
    aliases: ['mcn']
    usage: /<command> [status|force] [check|online|offline]
  onlinemode:
    description: Enable/Disable online mode
    aliases: ['om']
    usage: /<command> [status|enable|disable]

permissions:
  allowplayers.ap:
    description: Access the allowplayers command
    default: op
  allowplayers.ap.mod:
    description: Accept/reject a pending request
    default: op
  allowplayers.ap.reload:
    description: Reload the configuration
    default: op
  allowplayers.mcn:
    description: Access the mcnet command
    default: op
  allowplayers.mcn.force:
    description: Force minecraft.net mode
    default: op
  allowplayers.onlinemode:
    description: Set the server's online mode
    default: op
  allowplayers.msg.notify:
    description: View Minecraft.net status messages
    default: op
  allowplayers.msg.request:
    description: View messages about requests
    default: op
    
